# Generated by Django 2.0.3 on 2021-04-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(default='', max_length=30, verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='请输入标题', max_length=30, verbose_name='标题')),
                ('body', models.TextField(default='请输入正文', verbose_name='正文')),
                ('auth', models.CharField(blank=True, default='admin', max_length=30, null=True, verbose_name='作者')),
                ('detail', models.TextField(default='请添加备注', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.ArticleClassify', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
            },
        ),
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('mail', models.CharField(max_length=30, verbose_name='邮箱')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
            ],
            options={
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30, verbose_name='银行名称')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('point', models.CharField(max_length=30, verbose_name='网点')),
            ],
            options={
                'verbose_name_plural': '银行卡',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30, verbose_name='书名')),
                ('auth', models.ManyToManyField(to='MyApp.Auther', verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '书籍详情',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=30, verbose_name='卡号')),
                ('card_user', models.CharField(max_length=30, verbose_name='姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '银行卡_基本信息',
                'verbose_name_plural': '银行卡账户',
            },
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=30, verbose_name='手机号')),
                ('mail', models.CharField(max_length=30, verbose_name='邮箱')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('address', models.CharField(max_length=30, verbose_name='详细地址')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyApp.Card', verbose_name='卡号')),
            ],
            options={
                'verbose_name': '账户_个人资料',
                'verbose_name_plural': '账户_个人资料',
            },
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=30, verbose_name='卡号')),
                ('card_user', models.CharField(max_length=30, verbose_name='姓名')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.Bank', verbose_name='选择银行')),
            ],
            options={
                'verbose_name_plural': '卡信息',
            },
        ),
        migrations.CreateModel(
            name='FileImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='up_image', verbose_name='上传图片')),
                ('files', models.FileField(blank=True, null=True, upload_to='up_file', verbose_name='上传文件')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '上传文件和图片',
                'verbose_name_plural': '上传文件和图片',
            },
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True)),
                ('add', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(default='123@qq.com', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PersonUser',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RestCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default='', max_length=30, verbose_name='卡号')),
                ('card_user', models.CharField(default='', max_length=30, verbose_name='姓名')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '银行卡账户——基本信息',
                'verbose_name_plural': '银行账户信息',
            },
        ),
        migrations.CreateModel(
            name='Stendent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('qq', models.IntegerField(verbose_name='qq号')),
                ('sex', models.CharField(max_length=50, verbose_name='性别')),
                ('add', models.CharField(max_length=30, verbose_name='地址')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('creattime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '个人信息表',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学生id')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('score', models.IntegerField(verbose_name='分数')),
            ],
            options={
                'verbose_name': '学生成绩表',
                'verbose_name_plural': '学生成绩表',
            },
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='', max_length=30, verbose_name='学号')),
                ('name', models.CharField(default='', max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='', max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(default='', verbose_name='年龄')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='TestHan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.IntegerField()),
                ('tel', models.BigIntegerField()),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('timeser', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TestTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creattime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
