# Generated by Django 2.0.3 on 2021-03-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True)),
                ('add', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(default='123@qq.com', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PersonUser',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stendent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('qq', models.IntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('creattime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestHan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.IntegerField()),
                ('tel', models.BigIntegerField()),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('timeser', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TestTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creattime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
