# Generated by Django 2.0.3 on 2021-03-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stendent',
            options={'verbose_name_plural': '个人信息表'},
        ),
        migrations.AlterField(
            model_name='stendent',
            name='add',
            field=models.CharField(max_length=30, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='stendent',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='stendent',
            name='creattime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stendent',
            name='email',
            field=models.CharField(max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='stendent',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='stendent',
            name='qq',
            field=models.IntegerField(verbose_name='qq号'),
        ),
        migrations.AlterField(
            model_name='stendent',
            name='sex',
            field=models.CharField(max_length=50, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='stendent',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
