# Generated by Django 2.0.3 on 2021-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20210330_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学生id')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('score', models.IntegerField(verbose_name='分数')),
            ],
            options={
                'verbose_name': '学生成绩表',
                'verbose_name_plural': '学生成绩表',
            },
        ),
    ]
