# Generated by Django 2.0.3 on 2021-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_card_carddetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='up_image', verbose_name='上传图片')),
                ('files', models.FileField(blank=True, null=True, upload_to='up_file', verbose_name='上传文件')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '上传文件和图片',
                'verbose_name_plural': '上传文件和图片',
            },
        ),
    ]
