# Generated by Django 2.0.3 on 2021-03-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20210325_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.IntegerField()),
                ('tel', models.BigIntegerField()),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('timeser', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
