# Generated by Django 2.0.3 on 2021-03-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_testtimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stendent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('qq', models.IntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
