# Generated by Django 2.0.3 on 2021-04-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_bank_cardinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('mail', models.CharField(max_length=30, verbose_name='邮箱')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
            ],
            options={
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30, verbose_name='书名')),
                ('auth', models.ManyToManyField(to='MyApp.Auther', verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '书籍详情',
            },
        ),
    ]
