# Generated by Django 2.0.3 on 2021-04-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_auther_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(default='', max_length=30, verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='请输入标题', max_length=30, verbose_name='标题')),
                ('body', models.TextField(default='请输入正文', verbose_name='正文')),
                ('auth', models.CharField(default='admin', max_length=30, verbose_name='作者')),
                ('detail', models.TextField(default='请添加备注', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.ArticleClassify', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
            },
        ),
    ]
