# Generated by Django 2.0.3 on 2021-04-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_articleclassify_articledetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='auth',
            field=models.CharField(blank=True, default='admin', max_length=30, null=True, verbose_name='作者'),
        ),
    ]
