# Generated by Django 2.0.3 on 2021-04-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_studentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default='', max_length=30, verbose_name='卡号')),
                ('card_user', models.CharField(default='', max_length=30, verbose_name='姓名')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '银行卡账户——基本信息',
                'verbose_name_plural': '银行账户信息',
            },
        ),
    ]
